- name: Check that mandatory variables are updated
  fail: msg="Please update the variables in satellite-clone-vars.yml (after copying satellite-clone-vars.sample.yml)"
  when: (public_backup_dir == "changeme") or (pr_number == "changeme")

- name: check if satellite-clone-vars.yml exists
  stat:
    path: roles/setup/files/satellite-clone-vars.yml
  register: sat_clone_vars

- name: check if satellite-hostname-vars.yml exists
  stat:
    path: roles/setup/files/satellite-hostname-vars.yml
  register: sat_hostname_vars

- name: fail if satellite-clone-vars.yml does not exist
  fail:
    msg: "satellite-clone-vars.yml was not found"
  when: sat_clone_vars.stat.exists == True

- name: fail if satellite-hostname-vars.yml does not exist
  fail:
    msg: "satellite-hostname-vars.yml was not found"
  when: sat_hostname_vars.stat.exists == True

- name: install the latest version of git
  yum:
    name: git
    state: latest

- name: install the latest version of wget
  yum:
    name: wget
    state: latest

- name: clone satellite-clone
  git:
    repo: https://github.com/RedHatSatellite/satellite-clone.git
    dest: /satellite-clone
    refspec: '+refs/pull/*:refs/heads/*'

- name: checkout PR branch
  command: git checkout {{ pr_number }}/head
  args:
    chdir: /satellite-clone

- name: chmod 755 helper scripts
  file:
    path: /satellite-clone/helpers
    mode: 0755
    recurse: yes

- name: update setup script
  command: sed -ie 's/RHEL_MAJOR_VERSION="0"/RHEL_MAJOR_VERSION="{{ rhel_version }}"/g' /satellite-clone/helpers/control_node_setup.sh

- name: run setup script
  command: sh /satellite-clone/helpers/control_node_setup.sh

- name: run reallocation script
  command: sh /satellite-clone/helpers/reallocate.sh

- name: copy satellite-clone-vars.yml
  copy:
    src: satellite-clone-vars.yml
    dest: /satellite-clone/satellite-clone-vars.yml 

- name: copy satellite-hostname-vars.yml
  copy:
    src: satellite-hostname-vars.yml
    dest: /satellite-clone/satellite-hostname-vars.yml 

- name: copy inventory file
  copy:
    src: /satellite-clone/inventory.sample
    dest: /satellite-clone/inventory
    remote_src: True

- name: update inventory 
  lineinfile:
    dest: /satellite-clone/inventory
    regexp: '^192\.168\.1\.100'
    line: "{{ inventory_hostname }}"

- name: create backup directory
  file: path=/backup state=directory
  
- name: get backup files
  command: wget -r -np -nd {{ public_backup_dir }}
  args:
    chdir: /backup
